### ISSUE TITLE
Nextcloud choose Path

### ISSUE THREAD

**Issue by wuast94** [keeporsweep/keeporsweep.net#3]
It would be nice to set a Path for a folder that i would like to clean

Example: 
set path to my directory where my handy upload is and then clean it. 
would be nice too to set a path for keep and a path for sweep. so my pictures gets sort

**Comment by jancborchardt** [comment]
Hi @wuast94 – this is a duplicate of https://github.com/keeporsweep/keeporsweep/issues/7 so I’m closing the issue. Let’s continue there (it’s a different repository for the Nextcloud app.)

Any contribution is very welcome! Thanks for your interest in Keep or Sweep! :)
